import { makeClient } from '../ipc/ipc.js';

export const clientStub = ipcRendererInjector => makeClient(ipcRendererInjector, 'Shakedex', [
  'fulfillSwap',
  'getFulfillments',
  'finalizeSwap',
  'transferLock',
  'transferCancel',
  'getListings',
  'finalizeLock',
  'finalizeCancel',
  'launchAuction',
  'downloadProofs',
  'restoreOneListing',
  'restoreOneFill',
  'getExchangeAuctions',
  'getExchangeSales',
  'listAuction',
  'getFeeInfo',
  'getBestBid',
  'getMarketHsdStatus',
  'getChannelExpiringNames',
  'getCommunityExpiringNames',
  'getGlobalExpiringNames',
  'getRecentlyExpiredNames',
  'getShakedexChannelSettings',
  'validateShakedexChannelHost',
  'setShakedexChannelHost',
  'resetShakedexChannelHost',
]);
